spring:
  profiles:
    active: dev

#dev ayarları
---
spring:
  profiles: dev
  application:
    name: happypoint
  datasource:
    url:  jdbc:postgresql://localhost:5432/happypoint
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 5000

log:
  file:
    path: ${user.home}/logs/${spring.application.name}

amazon:
  dynamodb:
    endpoint:
  aws:
    accesskey: AKIAIT2SXTUEGXZ6A7BQ
    secretkey: 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

#prod ayarları
---

spring:
  profiles: prod
  application:
    name: happypoint

server:
  port: 5000

log:
  file:
    path: ${user.home}/logs/${spring.application.name}

amazon:
  dynamodb:
    endpoint:
  aws:
    accesskey: AKIAIT2SXTUEGXZ6A7BQ
    secretkey: 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